### ISSUE TITLE
Illegal code in "should not use values for patterns"

### ISSUE THREAD

**Issue by mars0i** [pyrocat101/ocaml-style-guide#1]
In #3 "Function Arguments Should Not Use Values for Patterns", under Pattern Matching, the second definition of `fact` needs a `rec` after `let` in order to compile.  The first definition would not be legal OCaml even after `rec` was added, afaik.  (This style guide is copied from an OCaml style guide that was copied from an SML style guide.   It looks like the author of the previous OCaml style guide simply replaced SML's `fun` with OCaml's `let` in the first definition.)

(The same errors are repeated in other versions of this guide, e.g. https://www.seas.upenn.edu/~cis341/current/programming_style.shtml#25, but they're not on github, so it's less convenient to comment, and I'm not going to hunt down every version of this guide. :-)

**Comment by pyrocat101** [comment]
Please refer to https://ocaml.org/learn/tutorials/guidelines.html for an actively maintained and up-to-date guideline.
